### PR TITLE
javascript.ashx CS1501 compilation error fix

### PR DESCRIPTION
**Pull request by atifaziz**
Fixes issue #70
Possibly was broken since df18da8b20fe4b08420fa5f38fda36684d6ed362

### CODE REVIEW

**Comment by shanselman** [comment]
Thanks!
